(function () {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const svg = $('drawing');
  const objects = $('objects');
  const layersRoot = $('layerList');
  const actions = document.querySelector('.actions');
  const desktopDialog = $('desktopDialog');
  const desktopResult = $('desktopResult');
  const fileInput = document.createElement('input');
  const open = document.createElement('button');
  const state = { tool: 'select', items: [], layers: [{ id: 'geometry', name: 'Geometry', visible: true }], activeLayer: 'geometry', selected: null, pointer: null, pan: { x: 0, y: 0 }, zoom: 1, grid: true, docName: 'Untitled drawing', history: [], future: [], dirty: false, space: false };

  open.id = 'open'; open.className = 'secondary'; open.textContent = 'Open file'; open.title = 'Open an SVG, STEP, or JSON geometry file';
  fileInput.type = 'file'; fileInput.accept = '.svg,.step,.stp,.json,application/json,image/svg+xml'; fileInput.hidden = true;
  actions.insertBefore(open, $('save')); actions.appendChild(fileInput);

  const number = '[-+]?\\d*\\.?\\d+(?:[Ee][-+]?\\d+)?';
  const clone = (value) => JSON.parse(JSON.stringify(value));
  const id = () => `shape-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
  const notify = (message, level = 'info') => window.vibeOS?.notify(message, { level, timeoutMs: 2400 });
  function setSaved(dirty) { state.dirty = dirty; $('saved').textContent = dirty ? 'Unsaved' : 'Saved'; $('saved').classList.toggle('is-dirty', dirty); }
  function persist() { const write = window.vibeOS?.storage.write('cad-drawing', { items: state.items, layers: state.layers, activeLayer: state.activeLayer, docName: state.docName, grid: state.grid }); if (write?.catch) write.catch(() => {}); }
  function commit(mutator) { state.history.push({ items: clone(state.items), layers: clone(state.layers), activeLayer: state.activeLayer }); state.future = []; mutator(); setSaved(true); persist(); render(); }
  function restore(snapshot) { state.items = snapshot.items; state.layers = snapshot.layers?.length ? snapshot.layers : [{ id: 'geometry', name: 'Geometry', visible: true }]; state.activeLayer = state.layers.some((layer) => layer.id === snapshot.activeLayer) ? snapshot.activeLayer : state.layers[0].id; state.selected = null; persist(); render(); }
  function undo() { if (!state.history.length) return notify('Nothing to undo', 'warning'); state.future.push({ items: clone(state.items), layers: clone(state.layers), activeLayer: state.activeLayer }); restore(state.history.pop()); setSaved(true); }
  function redo() { if (!state.future.length) return notify('Nothing to redo', 'warning'); state.history.push({ items: clone(state.items), layers: clone(state.layers), activeLayer: state.activeLayer }); restore(state.future.pop()); setSaved(true); }
  function cameraView() { const width = 1000 / state.zoom, height = 620 / state.zoom; return { x: state.pan.x + (1000 - width) / 2, y: state.pan.y + (620 - height) / 2, width, height }; }
  function canvasPoint(event) { const rect = svg.getBoundingClientRect(), view = cameraView(); return { x: view.x + (event.clientX - rect.left) * view.width / rect.width, y: view.y + (event.clientY - rect.top) * view.height / rect.height }; }
  function format(value) { return Number.isFinite(value) ? String(Math.round(value * 100) / 100) : '0'; }
  function render() {
    const view = cameraView(); svg.setAttribute('viewBox', `${view.x} ${view.y} ${view.width} ${view.height}`); $('gridBg').style.display = state.grid ? '' : 'none'; document.querySelector('.switch').classList.toggle('on', state.grid); $('zoomLabel').textContent = `${Math.round(state.zoom * 100)}%`; $('docName').textContent = state.docName; $('count').textContent = `${state.items.length} object${state.items.length === 1 ? '' : 's'}`; objects.replaceChildren();
    state.items.forEach((item) => { const layer = state.layers.find((entry) => entry.id === (item.layerId || 'geometry')); if (layer && !layer.visible) return; const element = document.createElementNS('http://www.w3.org/2000/svg', item.type === 'circle' ? 'circle' : item.type === 'line' ? 'path' : 'rect'); if (item.type === 'circle') { element.setAttribute('cx', item.x); element.setAttribute('cy', item.y); element.setAttribute('r', item.r); } else if (item.type === 'line') element.setAttribute('d', `M ${item.x} ${item.y} L ${item.x + item.w} ${item.y + item.h}`); else { element.setAttribute('x', Math.min(item.x, item.x + item.w)); element.setAttribute('y', Math.min(item.y, item.y + item.h)); element.setAttribute('width', Math.abs(item.w)); element.setAttribute('height', Math.abs(item.h)); } element.setAttribute('fill', item.type === 'rect' && item.fill ? item.fill : 'none'); element.setAttribute('stroke', item.stroke || 'var(--accent)'); element.setAttribute('stroke-width', item.sw || 3); element.setAttribute('vector-effect', 'non-scaling-stroke'); element.dataset.id = item.id; element.classList.toggle('selected', item.id === state.selected); objects.appendChild(element); });
    renderInspector(); renderLayers();
  }
  function setInteractionStatus(message, level = 'info') { const status = document.querySelector('.status span:first-child'); if (!status) return; status.innerHTML = `<b class="green"></b> ${message}`; status.dataset.level = level; }
  function renderInspector() { const selected = state.items.find((item) => item.id === state.selected) || null; state.selected = selected?.id || null; $('empty').hidden = !!selected; $('details').hidden = !selected; if (!selected) return; $('type').textContent = selected.type[0].toUpperCase() + selected.type.slice(1); $('layerName').textContent = state.layers.find((layer) => layer.id === (selected.layerId || 'geometry'))?.name || 'Geometry'; $('x').value = format(selected.x); $('y').value = format(selected.y); $('w').value = format(selected.type === 'circle' ? selected.r * 2 : selected.w); $('h').value = format(selected.type === 'circle' ? selected.r * 2 : selected.h); $('stroke').value = selected.stroke || '#6d83ff'; $('sw').value = format(selected.sw || 3); }
  function renderLayers() { layersRoot.replaceChildren(); state.layers.forEach((layer) => { const row = document.createElement('div'); row.className = `layer${layer.id === state.activeLayer ? ' active' : ''}`; row.dataset.layer = layer.id; row.innerHTML = `<button class="eye" aria-label="Toggle ${layer.name} visibility">${layer.visible ? '◉' : '○'}</button><span>${layer.name}</span><small>${state.items.filter((item) => (item.layerId || 'geometry') === layer.id).length}</small>`; row.addEventListener('click', () => { state.activeLayer = layer.id; render(); }); row.querySelector('.eye').addEventListener('click', (event) => { event.stopPropagation(); layer.visible = !layer.visible; persist(); render(); }); layersRoot.appendChild(row); }); }
  function setTool(tool) { state.tool = tool; document.querySelectorAll('.tool[data-tool]').forEach((button) => button.classList.toggle('active', button.dataset.tool === tool)); $('hint').textContent = tool === 'select' ? 'Click an object to inspect it' : `Click and drag to draw a ${tool}`; setInteractionStatus(tool === 'select' ? 'Ready' : `Drawing ${tool}`); svg.classList.toggle('drawing-mode', tool !== 'select'); }
  function addShape(point) { return { id: id(), type: state.tool, x: point.x, y: point.y, w: 0, h: 0, r: 0, stroke: '#6d83ff', sw: 3, layerId: state.activeLayer }; }
  function parseSvg(text) { const doc = new DOMParser().parseFromString(text, 'image/svg+xml'); if (doc.querySelector('parsererror')) throw new Error('Invalid SVG'); const items = []; doc.querySelectorAll('rect,circle,line').forEach((node) => { const attr = (name) => Number(node.getAttribute(name)); const stroke = node.getAttribute('stroke') || '#6d83ff', sw = Number(node.getAttribute('stroke-width')) || 3; if (node.tagName === 'circle') items.push({ id: id(), type: 'circle', x: attr('cx') || 0, y: attr('cy') || 0, r: Math.abs(attr('r') || 0), w: 0, h: 0, stroke, sw, layerId: 'geometry' }); else if (node.tagName === 'line') items.push({ id: id(), type: 'line', x: attr('x1') || 0, y: attr('y1') || 0, w: (attr('x2') || 0) - (attr('x1') || 0), h: (attr('y2') || 0) - (attr('y1') || 0), r: 0, stroke, sw, layerId: 'geometry' }); else items.push({ id: id(), type: 'rect', x: attr('x') || 0, y: attr('y') || 0, w: attr('width') || 0, h: attr('height') || 0, r: 0, stroke, sw, layerId: 'geometry' }); }); if (!items.length) throw new Error('No supported 2D geometry found'); return items; }
  function parseJson(text) { const data = JSON.parse(text), list = Array.isArray(data) ? data : data.items; if (!Array.isArray(list)) throw new Error('Geometry must be an array or an items array'); const items = list.filter((item) => ['line', 'rect', 'circle'].includes(item.type)).map((item) => ({ id: item.id || id(), type: item.type, x: Number(item.x) || 0, y: Number(item.y) || 0, w: Number(item.w) || 0, h: Number(item.h) || 0, r: Math.abs(Number(item.r) || 0), stroke: item.stroke || '#6d83ff', sw: Number(item.sw) || 3, layerId: 'geometry' })); if (!items.length) throw new Error('No supported 2D geometry found'); return items; }
  function parseStep(text) { const points = new Map(), directions = new Map(), vectors = new Map(), placements = new Map(), output = []; let match; const pointRe = new RegExp(`#(\\d+)\\s*=\\s*CARTESIAN_POINT\\s*\\([^;]*?\\(\\s*(${number})\\s*,\\s*(${number})\\s*,\\s*(${number})\\s*\\)\\s*\\)`, 'gi'); while ((match = pointRe.exec(text))) points.set(match[1], { x: Number(match[2]), y: Number(match[3]) }); const directionRe = new RegExp(`#(\\d+)\\s*=\\s*DIRECTION\\s*\\([^;]*?\\(\\s*(${number})\\s*,\\s*(${number})\\s*,\\s*(${number})\\s*\\)`, 'gi'); while ((match = directionRe.exec(text))) directions.set(match[1], { x: Number(match[2]), y: Number(match[3]) }); const vectorRe = new RegExp(`#(\\d+)\\s*=\\s*VECTOR\\s*\\([^,;]*,\\s*#(\\d+)\\s*,\\s*(${number})\\s*\\)`, 'gi'); while ((match = vectorRe.exec(text))) vectors.set(match[1], { dir: match[2], length: Number(match[3]) }); const placementRe = /#(\d+)\s*=\s*AXIS2_PLACEMENT_3D\s*\([^,]*,\s*#(\d+)\s*,\s*#(\d+)/gi; while ((match = placementRe.exec(text))) placements.set(match[1], { point: match[2] }); const project = (point) => ({ x: 500 + point.x * 4, y: 310 - point.y * 4 }); const addLine = (a, b) => { const start = project(a), end = project(b); output.push({ id: id(), type: 'line', x: start.x, y: start.y, w: end.x - start.x, h: end.y - start.y, r: 0, stroke: '#6d83ff', sw: 3, layerId: 'geometry' }); }; const polyRe = /#(\d+)\s*=\s*POLYLINE\s*\([^;]*?\(([^)]*)\)\s*\)/gi; while ((match = polyRe.exec(text))) { const ids = [...match[2].matchAll(/#(\d+)/g)].map((entry) => entry[1]); for (let i = 1; i < ids.length; i++) if (points.has(ids[i - 1]) && points.has(ids[i])) addLine(points.get(ids[i - 1]), points.get(ids[i])); } const lineRe = /#(\d+)\s*=\s*LINE\s*\([^,]*,\s*#(\d+)\s*,\s*#(\d+)\s*\)/gi; while ((match = lineRe.exec(text))) { const base = points.get(match[2]), vector = vectors.get(match[3]), direction = vector && directions.get(vector.dir); if (base && direction) { const length = vector.length || 80; addLine({ x: base.x - direction.x * length / 2, y: base.y - direction.y * length / 2 }, { x: base.x + direction.x * length / 2, y: base.y + direction.y * length / 2 }); } } if (!output.length) throw new Error('No supported 2D geometry found'); return output; }
  function exportSvg() { const copy = svg.cloneNode(true); copy.querySelector('#gridBg')?.remove(); copy.querySelector('#crosshair')?.remove(); copy.querySelectorAll('.selected').forEach((node) => node.classList.remove('selected')); copy.setAttribute('viewBox', '0 0 1000 620'); copy.setAttribute('width', '1000'); copy.setAttribute('height', '620'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(copy)], { type: 'image/svg+xml' })); link.download = `${state.docName.replace(/\.[^.]+$/, '') || 'drawing'}.svg`; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); setInteractionStatus('Exported'); notify(`${link.download} exported`, 'success'); }
  function formatDesktopState(value) {
    if (!value) return 'No desktop state returned.';
    if (typeof value === 'string') return value;
    return JSON.stringify(value, null, 2);
  }
  async function showDesktopState() {
    desktopDialog.hidden = false;
    desktopResult.textContent = 'Retrieving the current desktop state…';
    try {
      const response = await window.vibeOS?.ai.command('show me the desktop state', { scope: 'world', output: 'result' });
      desktopResult.textContent = formatDesktopState(response?.value || response?.summary);
    } catch (error) {
      desktopResult.textContent = `Could not retrieve desktop state. ${error?.message || 'The request failed.'}`;
      notify('Desktop state request failed', 'error');
    }
  }
  function zoomAt(factor, point) { const before = point || { x: 500, y: 310 }, oldView = cameraView(); state.zoom = Math.max(0.45, Math.min(4, state.zoom * factor)); const nextView = cameraView(); state.pan.x += (before.x - oldView.x) - (before.x - nextView.x); state.pan.y += (before.y - oldView.y) - (before.y - nextView.y); render(); }
  document.querySelectorAll('.tool[data-tool]').forEach((button) => button.addEventListener('click', () => setTool(button.dataset.tool))); $('undo').addEventListener('click', undo); $('redo').addEventListener('click', redo); $('save').addEventListener('click', exportSvg); $('desktopState').addEventListener('click', showDesktopState); $('refreshDesktop').addEventListener('click', showDesktopState); $('closeDesktop').addEventListener('click', () => { desktopDialog.hidden = true; }); desktopDialog.addEventListener('click', (event) => { if (event.target === desktopDialog) desktopDialog.hidden = true; }); $('zoomIn').addEventListener('click', () => zoomAt(1.15)); $('zoomOut').addEventListener('click', () => zoomAt(1 / 1.15)); $('zoomFit').addEventListener('click', () => { state.zoom = 1; state.pan = { x: 0, y: 0 }; render(); }); $('grid').addEventListener('click', () => { state.grid = !state.grid; persist(); render(); }); $('addLayer').addEventListener('click', () => { const layer = { id: `layer-${Date.now()}`, name: `Layer ${state.layers.length + 1}`, visible: true }; commit(() => { state.layers.push(layer); state.activeLayer = layer.id; }); notify(`${layer.name} added`, 'success'); }); $('delete').addEventListener('click', () => { if (!state.selected) return notify('Select an object first', 'warning'); commit(() => { state.items = state.items.filter((item) => item.id !== state.selected); state.selected = null; }); });
  ['x', 'y', 'w', 'h', 'sw', 'stroke'].forEach((key) => $(key).addEventListener('change', () => { const selected = state.items.find((item) => item.id === state.selected); if (!selected) return; const value = key === 'stroke' ? $(key).value : Number($(key).value); if (key !== 'stroke' && !Number.isFinite(value)) return renderInspector(); commit(() => { if (key === 'w' && selected.type === 'circle') selected.r = Math.abs(value) / 2; else if (key === 'h' && selected.type === 'circle') selected.r = Math.abs(value) / 2; else selected[key] = key === 'stroke' ? value : Math.max(-5000, Math.min(5000, value)); }); }));
  svg.addEventListener('pointerdown', (event) => { const point = canvasPoint(event), panGesture = event.button === 1 || state.space || event.button === 2; if (panGesture) { state.pointer = { mode: 'pan', x: event.clientX, y: event.clientY, pan: { ...state.pan } }; svg.setPointerCapture(event.pointerId); return; } if (event.button !== 0) return; if (state.tool === 'select') { state.selected = event.target.closest('[data-id]')?.dataset.id || null; render(); return; } state.pointer = { mode: 'draw', start: point, shape: addShape(point) }; svg.setPointerCapture(event.pointerId); });
  svg.addEventListener('pointermove', (event) => { const point = canvasPoint(event); $('coords').textContent = `X ${format(point.x)}   Y ${format(point.y)}`; if (!state.pointer || state.pointer.mode !== 'pan') return; const view = cameraView(); state.pan.x = state.pointer.pan.x - (event.clientX - state.pointer.x) * view.width / svg.clientWidth; state.pan.y = state.pointer.pan.y - (event.clientY - state.pointer.y) * view.height / svg.clientHeight; render(); });
  svg.addEventListener('pointerup', (event) => { const gesture = state.pointer; state.pointer = null; if (!gesture || gesture.mode !== 'draw') return; const point = canvasPoint(event), shape = gesture.shape; if (shape.type === 'circle') shape.r = Math.hypot(point.x - gesture.start.x, point.y - gesture.start.y); else { shape.w = point.x - gesture.start.x; shape.h = point.y - gesture.start.y; } if ((shape.type === 'circle' && shape.r < 3) || (shape.type !== 'circle' && Math.abs(shape.w) < 3 && Math.abs(shape.h) < 3)) return render(); commit(() => { state.items.push(shape); state.selected = shape.id; }); }); svg.addEventListener('pointercancel', () => { state.pointer = null; }); svg.addEventListener('wheel', (event) => { event.preventDefault(); zoomAt(event.deltaY < 0 ? 1.1 : 1 / 1.1, canvasPoint(event)); }, { passive: false });
  svg.addEventListener('contextmenu', async (event) => { event.preventDefault(); const choice = await window.vibeOS?.contextMenu.open([{ id: 'delete', label: 'Delete selection', disabled: !state.selected }, { id: 'select', label: 'Use select tool' }, { id: 'fit', label: 'Fit view' }], { x: event.clientX, y: event.clientY }); if (choice === 'delete') $('delete').click(); if (choice === 'select') setTool('select'); if (choice === 'fit') $('zoomFit').click(); });
  open.addEventListener('click', () => fileInput.click()); fileInput.addEventListener('change', async (event) => { const file = event.target.files[0]; if (!file) return; try { const text = await file.text(), lower = file.name.toLowerCase(), items = lower.endsWith('.step') || lower.endsWith('.stp') ? parseStep(text) : lower.endsWith('.svg') ? parseSvg(text) : parseJson(text); commit(() => { state.items = items; state.layers = [{ id: 'geometry', name: 'Geometry', visible: true }]; state.activeLayer = 'geometry'; state.selected = null; state.docName = file.name; }); setSaved(false); persist(); notify(`${file.name} opened`, 'success'); } catch (error) { notify(error.message || 'Could not open that file', 'error'); } finally { fileInput.value = ''; } });
  document.addEventListener('keydown', (event) => { if (event.target.matches('input')) return; const key = event.key.toLowerCase(); if (key === ' ' && !event.repeat) { state.space = true; svg.classList.add('panning'); event.preventDefault(); } if ((event.metaKey || event.ctrlKey) && key === 'z') { event.preventDefault(); event.shiftKey ? redo() : undo(); } else if ((event.metaKey || event.ctrlKey) && key === 'y') { event.preventDefault(); redo(); } else if ((event.metaKey || event.ctrlKey) && key === 's') { event.preventDefault(); exportSvg(); } else if ((event.metaKey || event.ctrlKey) && key === 'o') { event.preventDefault(); open.click(); } else if (!event.metaKey && !event.ctrlKey && ({ v: 'select', l: 'line', r: 'rect', c: 'circle' })[key]) setTool(({ v: 'select', l: 'line', r: 'rect', c: 'circle' })[key]); if (key === 'delete' && state.selected) $('delete').click(); if (key === 'escape') { state.pointer = null; state.selected = null; render(); } }); document.addEventListener('keyup', (event) => { if (event.key === ' ') { state.space = false; svg.classList.remove('panning'); } });
  window.vibeOS?.commands.setContext(() => ({ tool: state.tool, selected: state.selected, objectCount: state.items.length, activeLayer: state.activeLayer })); window.vibeOS?.commands.register({ id: 'cad-export-svg', title: 'Export drawing as SVG', detail: 'Download the current model space as an SVG file' });
  (async function init() { try { const saved = await window.vibeOS?.storage.read('cad-drawing'); if (saved && Array.isArray(saved.items)) { state.items = saved.items.map((item) => ({ ...item, layerId: item.layerId || 'geometry' })); state.layers = saved.layers?.length ? saved.layers : [{ id: 'geometry', name: 'Geometry', visible: true }]; state.activeLayer = state.layers.some((layer) => layer.id === saved.activeLayer) ? saved.activeLayer : state.layers[0].id; state.docName = saved.docName || state.docName; state.grid = saved.grid !== false; } } catch (error) { notify('Saved drawing could not be read', 'warning'); } render(); }());
}());
