const fallback={tabs:[{id:'app.js',content:`const greeting = "Hello, VibeOS";\n\nfunction start() {\n  console.log(greeting);\n}\n\nstart();`},{id:'index.html',content:`<!doctype html>\n<html lang="en">\n  <body>\n    <main id="app"></main>\n  </body>\n</html>`},{id:'styles.css',content:`:root {\n  --accent: #a89dfc;\n}\n\nbody {\n  margin: 0;\n}`},{id:'README.md',content:`# My Project\n\nA small, focused workspace.`}],activeTabId:'app.js',selection:{start:0,end:0}};
let appState=fallback;let current='app.js'; const editor=document.querySelector('#editor'),gutter=document.querySelector('#gutter'),highlight=document.querySelector('#highlight');
function escape(value){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function highlightCode(value,name){let html=escape(value);if(/\.js$/.test(name))html=html.replace(/(\/\/.*$)/gm,'<i>$1</i>').replace(/("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')/g,'<b>$1</b>').replace(/\b(const|let|var|function|return|if|else|new|true|false|null)\b/g,'<strong>$1</strong>');else if(/\.html?$/.test(name))html=html.replace(/(&lt;\/?[\w-]+[^&]*?&gt;)/g,'<strong>$1</strong>');else if(/\.css$/.test(name))html=html.replace(/(--?[\w-]+|[.#][\w-]+)/g,'<b>$1</b>');else if(/\.md$/.test(name))html=html.replace(/^(#+ .*)$/gm,'<strong>$1</strong>');return html}
function renderLines(){gutter.textContent=Array.from({length:Math.max(1,editor.value.split('\n').length)},(_,i)=>i+1).join('\n');highlight.innerHTML=highlightCode(editor.value,current)}
function tab(name){return appState.tabs.find(item=>item.id===name)}
function openFile(name){current=name;appState.activeTabId=name;editor.value=tab(name)?.content??'';document.querySelectorAll('[data-file]').forEach(x=>x.classList.toggle('active',x.dataset.file===name));document.querySelector('#crumbFile').textContent=name;const lang=name.endsWith('.js')?'JavaScript':name.endsWith('.css')?'CSS':name.endsWith('.html')?'HTML':'Markdown';document.querySelector('#language').textContent=lang;document.querySelector('#langStatus').textContent=lang;renderLines();editor.focus()}
async function save(){const active=tab(current);if(active)active.content=editor.value;try{await window.vibeOS.state.write(appState);document.querySelector('#status').textContent='Saved'}catch(error){document.querySelector('#status').textContent=error.message||'Save failed'}setTimeout(()=>document.querySelector('#status').textContent='Ready',1400)}
document.querySelectorAll('[data-file]').forEach(x=>x.addEventListener('click',()=>openFile(x.dataset.file)));editor.addEventListener('input',()=>{const active=tab(current);if(active)active.content=editor.value;renderLines();document.querySelector('#status').textContent='Unsaved changes'});editor.addEventListener('select',()=>appState.selection={start:editor.selectionStart,end:editor.selectionEnd});editor.addEventListener('scroll',()=>{highlight.scrollTop=editor.scrollTop;highlight.scrollLeft=editor.scrollLeft;gutter.scrollTop=editor.scrollTop});editor.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='s'){e.preventDefault();save()} });
document.querySelector('#themeBtn').onclick=()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';
const palette=document.querySelector('#palette');
function togglePalette(){palette.classList.toggle('hidden');if(!palette.classList.contains('hidden'))document.querySelector('#paletteInput').focus()}
document.querySelector('#paletteBtn').onclick=togglePalette;
palette.onclick=e=>{if(e.target===palette)togglePalette()};
document.querySelector('#paletteInput').addEventListener('keydown',async e=>{
  if(e.key!=='Enter'||!e.target.value.trim())return;
  e.preventDefault();e.stopImmediatePropagation();
  const command=e.target.value.trim();
  document.querySelector('#status').textContent='Running command…';
  try{
    if(!window.vibeOS?.ai?.command)throw new Error('AI commands are unavailable while the system is disconnected.');
    const result=await window.vibeOS.ai.command(command,{scope:'app',context:{file:current,selection:{start:editor.selectionStart,end:editor.selectionEnd}},output:'modify'});
    document.querySelector('#status').textContent=result?.summary||'Command complete';
  }catch(error){document.querySelector('#status').textContent=error instanceof Error?error.message:'Command failed'}
  e.target.value='';palette.classList.add('hidden');editor.focus();
});
document.querySelectorAll('[data-command]').forEach(x=>x.onclick=()=>{const c=x.dataset.command;if(c==='save')save();if(c==='theme')document.querySelector('#themeBtn').click();if(c==='find'){document.querySelector('#findbar').classList.remove('hidden');document.querySelector('#findInput').focus()}if(c==='new')newFile();togglePalette()});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();togglePalette()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='f'){e.preventDefault();document.querySelector('#findbar').classList.remove('hidden');document.querySelector('#findInput').focus()}if(e.key==='Escape'){palette.classList.add('hidden');document.querySelector('#findbar').classList.add('hidden')}});document.querySelector('#findClose').onclick=()=>document.querySelector('#findbar').classList.add('hidden');document.querySelector('#findInput').oninput=e=>{const n=(editor.value.match(new RegExp(e.target.value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi'))||[]).length;document.querySelector('#findCount').textContent=e.target.value?n+' matches':''};
function newFile(){const name='untitled-'+appState.tabs.length+'.txt';appState.tabs.push({id:name,content:''});const b=document.createElement('button');b.className='file';b.dataset.file=name;b.innerHTML='<span class="md">T</span> '+name;b.onclick=()=>openFile(name);document.querySelector('.tree').append(b);openFile(name)}document.querySelector('#newFile').onclick=newFile;document.querySelector('#runBtn').onclick=()=>{document.querySelector('#status').textContent='Build successful';setTimeout(()=>document.querySelector('#status').textContent='Ready',1600)};document.querySelector('#splitBtn').onclick=()=>{document.querySelector('#status').textContent='Split view is ready';setTimeout(()=>document.querySelector('#status').textContent='Ready',1400)};document.querySelectorAll('.menubar>button:not(#themeBtn):not(#paletteBtn)').forEach(b=>b.onclick=()=>{document.querySelector('#status').textContent=b.textContent+' menu';setTimeout(()=>document.querySelector('#status').textContent='Ready',1000)});addEventListener('vibeos:ready',async()=>{try{const saved=await window.vibeOS.state.read();if(saved.state?.tabs?.length)appState=saved.state;openFile(appState.activeTabId||appState.tabs[0].id);window.vibeOS.state.subscribe(next=>{appState=next.state;openFile(appState.activeTabId||appState.tabs[0].id)})}catch{openFile('app.js')}});openFile('app.js');
