const files={"app.js":`const greeting = "Hello, VibeOS";\n\nfunction start() {\n  console.log(greeting);\n}\n\nstart();`,"index.html":`<!doctype html>\n<html lang="en">\n  <body>\n    <main id="app"></main>\n  </body>\n</html>`,"styles.css":`:root {\n  --accent: #a89dfc;\n}\n\nbody {\n  margin: 0;\n}`,"README.md":`# My Project\n\nA small, focused workspace.`};
let current='app.js'; const editor=document.querySelector('#editor'),gutter=document.querySelector('#gutter');
function renderLines(){gutter.textContent=Array.from({length:Math.max(1,editor.value.split('\n').length)},(_,i)=>i+1).join('\n')}
function openFile(name){current=name;editor.value=files[name]??'';document.querySelectorAll('[data-file]').forEach(x=>x.classList.toggle('active',x.dataset.file===name));document.querySelector('#crumbFile').textContent=name;const lang=name.endsWith('.js')?'JavaScript':name.endsWith('.css')?'CSS':name.endsWith('.html')?'HTML':'Markdown';document.querySelector('#language').textContent=lang;document.querySelector('#langStatus').textContent=lang;renderLines();editor.focus()}
function save(){files[current]=editor.value;document.querySelector('#status').textContent='Saved';setTimeout(()=>document.querySelector('#status').textContent='Ready',1400)}
document.querySelectorAll('[data-file]').forEach(x=>x.addEventListener('click',()=>openFile(x.dataset.file)));editor.addEventListener('input',()=>{renderLines();document.querySelector('#status').textContent='Unsaved changes'});editor.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='s'){e.preventDefault();save()} });
document.querySelector('#themeBtn').onclick=()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';
const palette=document.querySelector('#palette');function togglePalette(){palette.classList.toggle('hidden');if(!palette.classList.contains('hidden'))document.querySelector('#paletteInput').focus()};document.querySelector('#paletteBtn').onclick=togglePalette;palette.onclick=e=>{if(e.target===palette)togglePalette()};
document.querySelectorAll('[data-command]').forEach(x=>x.onclick=()=>{const c=x.dataset.command;if(c==='save')save();if(c==='theme')document.querySelector('#themeBtn').click();if(c==='find')document.querySelector('#findbar').classList.remove('hidden');if(c==='new')newFile();togglePalette()});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();togglePalette()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='f'){e.preventDefault();document.querySelector('#findbar').classList.remove('hidden');document.querySelector('#findInput').focus()}if(e.key==='Escape'){palette.classList.add('hidden');document.querySelector('#findbar').classList.add('hidden')}});document.querySelector('#findClose').onclick=()=>document.querySelector('#findbar').classList.add('hidden');document.querySelector('#findInput').oninput=e=>{const n=(editor.value.match(new RegExp(e.target.value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi'))||[]).length;document.querySelector('#findCount').textContent=e.target.value?n+' matches':''};
function newFile(){const name='untitled-'+(Object.keys(files).length)+'.txt';files[name]='';const b=document.createElement('button');b.className='file';b.dataset.file=name;b.innerHTML='<span class="md">T</span> '+name;b.onclick=()=>openFile(name);document.querySelector('.tree').append(b);openFile(name)}document.querySelector('#newFile').onclick=newFile;document.querySelector('#runBtn').onclick=()=>{document.querySelector('#status').textContent='Build successful';setTimeout(()=>document.querySelector('#status').textContent='Ready',1600)};openFile('app.js');
