const fallback={tabs:[{id:'app.js',content:`const greeting = "Hello, VibeOS";\n\nfunction start() {\n  console.log(greeting);\n}\n\nstart();`},{id:'index.html',content:`<!doctype html>\n<html lang="en">\n  <body>\n    <main id="app"></main>\n  </body>\n</html>`},{id:'styles.css',content:`:root {\n  --accent: #a89dfc;\n}\n\nbody {\n  margin: 0;\n}`},{id:'README.md',content:`# My Project\n\nA small, focused workspace.`}],activeTabId:'app.js',selection:{start:0,end:0}};
let appState=fallback;let current='app.js'; const editor=document.querySelector('#editor'),gutter=document.querySelector('#gutter'),highlight=document.querySelector('#highlight');
function escape(value){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function paintCode(html){return html.replace(/(\/\/.*$)/gm,'<i>$1</i>').replace(/("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')/g,'<b>$1</b>').replace(/\b(const|let|var|function|return|if|else|class|import|def|pass|True|False|None|new|true|false|null)\b/g,'<strong>$1</strong>')}
function highlightCode(value,name){let html=escape(value);if(/\.(js|py)$/.test(name))html=paintCode(html);else if(/\.html?$/.test(name))html=html.replace(/(&lt;\/?[\w-]+[^&]*?&gt;)/g,'<strong>$1</strong>');else if(/\.css$/.test(name))html=html.replace(/(--?[\w-]+|[.#][\w-]+)/g,'<b>$1</b>');else if(/\.md$/.test(name)){html=html.replace(/```([^\n]*)\n([\s\S]*?)```/g,(_,language,code)=>'<span class="fence">```'+language+'</span>\n'+paintCode(code)+'<span class="fence">```</span>').replace(/^(&gt;.*)$/gm,'<i>$1</i>').replace(/^(#{1,6} .*)$/gm,'<strong>$1</strong>').replace(/`([^`\n]+)`/g,'<em>$1</em>')}return html}
function renderLines(){gutter.textContent=Array.from({length:Math.max(1,editor.value.split('\n').length)},(_,i)=>i+1).join('\n');highlight.innerHTML=highlightCode(editor.value,current)}
function tab(name){return appState.tabs.find(item=>item.id===name)}
function languageFor(name){return name.endsWith('.py')?'Python':name.endsWith('.js')?'JavaScript':name.endsWith('.css')?'CSS':name.endsWith('.html')?'HTML':name.endsWith('.md')?'Markdown':'Plain Text'}
function indentUnitFor(name){return name.endsWith('.py')?'    ':'  '}
function lineStartAt(value,index){return value.lastIndexOf('\n',Math.max(0,index-1))+1}
function lineEndAt(value,index){const end=value.indexOf('\n',index);return end<0?value.length:end}
function leadingIndent(line){return line.match(/^[ \t]*/)?.[0]||''}
function indentWidth(indent,unit){return indent.split('').reduce((width,char)=>width+(char==='\t'?unit.length:1),0)}
function makeIndent(width){return ' '.repeat(Math.max(0,width))}
function shouldIndentAfter(line,name){const code=line.trimEnd();if(!code)return false;if(name.endsWith('.py'))return /:\s*(#.*)?$/.test(code)&&!/^\s*(return|raise|break|continue)\b/.test(code);if(name.endsWith('.html'))return /<(?!(?:\/|!|\?|area\b|base\b|br\b|col\b|embed\b|hr\b|img\b|input\b|link\b|meta\b|param\b|source\b|track\b|wbr\b))[^>]+>\s*$/.test(code)&&!/<[^>]+>.*<\/[^>]+>\s*$/.test(code);return /[({[]\s*(?:\/\/.*|\/\*.*\*\/)?$/.test(code)||/=>\s*$/.test(code)}
function shouldDedentLine(line,name){const trimmed=line.trim();if(name.endsWith('.py'))return /^(elif|else|except|finally)\b/.test(trimmed);if(name.endsWith('.html'))return /^<\//.test(trimmed);return /^[)}\]]/.test(trimmed)}
function replaceEditorValue(value,start,end){editor.setRangeText(value,start,end,'end');editor.dispatchEvent(new Event('input',{bubbles:true}))}
function indentSelection(outdent=false){const value=editor.value;const unit=indentUnitFor(current);let start=editor.selectionStart;let end=editor.selectionEnd;if(start!==end&&value[end-1]==='\n')end--;start=lineStartAt(value,start);end=lineEndAt(value,end);const selected=value.slice(start,end);const lines=selected.split('\n');const next=lines.map(line=>{if(outdent){if(line.startsWith(unit))return line.slice(unit.length);if(line.startsWith('\t'))return line.slice(1);return line.replace(/^ {1,4}/,'')}return unit+line}).join('\n');replaceEditorValue(next,start,end);editor.setSelectionRange(start,start+next.length);appState.selection={start:start,end:start+next.length};document.querySelector('#status').textContent=outdent?'Outdented selection':'Indented selection'}
function handleEditorKeydown(event){if(event.key==='Tab'){event.preventDefault();event.stopImmediatePropagation();if(editor.selectionStart!==editor.selectionEnd)indentSelection(event.shiftKey);else{const unit=indentUnitFor(current);const pos=editor.selectionStart;replaceEditorValue(unit,pos,pos);editor.setSelectionRange(pos+unit.length,pos+unit.length);appState.selection={start:pos+unit.length,end:pos+unit.length};document.querySelector('#status').textContent='Inserted indentation'}return}if(event.key==='Enter'&&!event.shiftKey&&!event.altKey&&!event.metaKey&&!event.ctrlKey){event.preventDefault();const pos=editor.selectionStart;const before=editor.value.slice(0,pos);const line=before.slice(before.lastIndexOf('\n')+1);const base=leadingIndent(line);let width=indentWidth(base,indentUnitFor(current));if(shouldIndentAfter(line,current))width+=indentUnitFor(current).length;const nextLine=editor.value.slice(editor.selectionEnd).split('\n')[0];if(shouldDedentLine(nextLine,current)&&!shouldIndentAfter(line,current))width=Math.max(0,width-indentUnitFor(current).length);const insertion='\n'+makeIndent(width);replaceEditorValue(insertion,pos,editor.selectionEnd);editor.setSelectionRange(pos+insertion.length,pos+insertion.length);appState.selection={start:editor.selectionStart,end:editor.selectionEnd};return}if(event.key==='Backspace'&&editor.selectionStart===editor.selectionEnd){const pos=editor.selectionStart;const unit=indentUnitFor(current);const lineStart=lineStartAt(editor.value,pos);const prefix=editor.value.slice(lineStart,pos);if(prefix.length>0&&/^\s+$/.test(prefix)&&prefix.length%unit.length===0){event.preventDefault();replaceEditorValue('',pos-unit.length,pos);editor.setSelectionRange(pos-unit.length,pos-unit.length);appState.selection={start:pos-unit.length,end:pos-unit.length}}}}
function dirtyTab(){return document.querySelector('.tab.active .dot')}
function setDirty(value){const dot=dirtyTab();if(dot)dot.hidden=!value}
function openFile(name){current=name;appState.activeTabId=name;editor.value=tab(name)?.content??'';document.querySelectorAll('[data-file]').forEach(x=>x.classList.toggle('active',x.dataset.file===name));document.querySelector('#crumbFile').textContent=name;const lang=languageFor(name);document.querySelector('#language').textContent=lang;document.querySelector('#langStatus').textContent=lang;setDirty(false);renderLines();editor.focus()}
async function persistState(){const saved=await window.vibeOS.state.write(appState);appState=saved.state}
function downloadCurrentFile(){const active=tab(current);if(!active)return;const blob=new Blob([editor.value],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=active.id;link.rel='noopener';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}
async function save({download=true}={}){const active=tab(current);if(active)active.content=editor.value;try{await persistState();if(download){downloadCurrentFile();window.vibeOS?.notify?.(`Downloaded ${current}`,{level:'success',timeoutMs:1800})}setDirty(false);document.querySelector('#status').textContent=download?'Downloaded':'Saved'}catch(error){document.querySelector('#status').textContent=error.message||'Save failed'}setTimeout(()=>document.querySelector('#status').textContent='Ready',1400)}
function renderTree(){const tree=document.querySelector('.tree'),tabs=document.querySelector('.tabs');tree.replaceChildren(...appState.tabs.map(item=>{const button=document.createElement('button');button.className='file'+(item.id===current?' active':'');button.dataset.file=item.id;button.innerHTML='<span class="'+(item.id.endsWith('.js')?'js':item.id.endsWith('.html')?'html':item.id.endsWith('.css')?'css':'md')+'">'+(item.id.endsWith('.js')?'JS':item.id.endsWith('.html')?'&lt;&gt;':item.id.endsWith('.css')?'#':'T')+'</span> '+escape(item.id);button.onclick=()=>openFile(item.id);button.oncontextmenu=async event=>{event.preventDefault();openFile(item.id);const action=await window.vibeOS.contextMenu.open([{id:'rename',label:'Rename…'},{id:'delete',label:'Delete'}],{x:event.clientX,y:event.clientY});if(action==='rename')renameFile(item.id);if(action==='delete')deleteFile(item.id)};return button}));const split=document.querySelector('#splitBtn');tabs.replaceChildren(...appState.tabs.map(item=>{const button=document.createElement('button');button.className='tab'+(item.id===current?' active':'');button.dataset.file=item.id;button.innerHTML='<span class="'+(item.id.endsWith('.js')?'js':item.id.endsWith('.html')?'html':item.id.endsWith('.css')?'css':'md')+'">'+(item.id.endsWith('.js')?'JS':item.id.endsWith('.html')?'&lt;&gt;':item.id.endsWith('.css')?'#':'T')+'</span> '+escape(item.id)+' <span class="dot" hidden></span><span class="close">×</span>';button.onclick=()=>openFile(item.id);return button}),Object.assign(document.createElement('span'),{className:'tab-space'}),split);}
function askFileName(title,initial){return new Promise(resolve=>{const overlay=document.createElement('div');overlay.className='file-dialog';overlay.innerHTML='<div role="dialog" aria-modal="true"><h2></h2><input aria-label="File name"><footer><button type="button">Cancel</button><button type="button">Continue</button></footer></div>';overlay.querySelector('h2').textContent=title;const input=overlay.querySelector('input');const finish=value=>{overlay.remove();resolve(value?.trim()||null)};input.value=initial;overlay.querySelector('button:first-of-type').onclick=()=>finish(null);overlay.querySelector('button:last-of-type').onclick=()=>finish(input.value);input.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();finish(input.value)}if(event.key==='Escape'){event.preventDefault();finish(null)}};document.body.append(overlay);input.focus();input.select()})}
async function renameFile(oldName){const name=await askFileName('Rename file',oldName);if(!name||name===oldName||tab(name))return;const item=tab(oldName);if(!item)return;item.id=name;if(current===oldName)current=name;appState.activeTabId=current;renderTree();openFile(current);save()}
function deleteFile(name){if(appState.tabs.length<2)return;appState.tabs=appState.tabs.filter(item=>item.id!==name);if(current===name)current=appState.tabs[0].id;appState.activeTabId=current;renderTree();openFile(current);void save({download:false})}
document.querySelectorAll('[data-file]').forEach(x=>x.addEventListener('click',()=>openFile(x.dataset.file)));editor.addEventListener('input',()=>{const active=tab(current);if(active)active.content=editor.value;setDirty(true);renderLines();document.querySelector('#status').textContent='Unsaved changes'});editor.addEventListener('select',()=>appState.selection={start:editor.selectionStart,end:editor.selectionEnd});editor.addEventListener('scroll',()=>{highlight.scrollTop=editor.scrollTop;highlight.scrollLeft=editor.scrollLeft;gutter.scrollTop=editor.scrollTop});editor.addEventListener('keydown',e=>{handleEditorKeydown(e);if((e.metaKey||e.ctrlKey)&&e.key==='s'){e.preventDefault();e.stopImmediatePropagation();void save()} },true);
document.querySelector('#themeBtn').onclick=()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';
window.vibeOS?.commands?.setContext(()=>({file:current,selection:{start:editor.selectionStart,end:editor.selectionEnd},content:editor.value}));
document.querySelectorAll('[data-command]').forEach(x=>x.onclick=()=>{const c=x.dataset.command;if(c==='save')save();if(c==='theme')document.querySelector('#themeBtn').click();if(c==='find'){document.querySelector('#findbar').classList.remove('hidden');document.querySelector('#findInput').focus()}if(c==='new')newFile();togglePalette()});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='f'){e.preventDefault();document.querySelector('#findbar').classList.remove('hidden');document.querySelector('#findInput').focus()}if(e.key==='Escape'){document.querySelector('#findbar').classList.add('hidden')}});document.querySelector('#findClose').onclick=()=>document.querySelector('#findbar').classList.add('hidden');document.querySelector('#findInput').oninput=e=>{const n=(editor.value.match(new RegExp(e.target.value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi'))||[]).length;document.querySelector('#findCount').textContent=e.target.value?n+' matches':''};
async function newFile(){const suggested='untitled-'+appState.tabs.length+'.txt';const name=await askFileName('New file',suggested);if(!name||tab(name))return;appState.tabs.push({id:name,content:''});renderTree();openFile(name);await save()}async function runCurrent(){await save();const source=editor.value;const language=languageFor(current);const status=document.querySelector('#status');if(language==='Python'){if(/(^|\n)\s*(def|class)\s+\w+[^:]*$/m.test(source)||/\bprint\s+[^()\n]/.test(source)){status.textContent='Python syntax error';return}status.textContent='Python checked successfully';return}if(language==='JavaScript'){try{new Function(source);status.textContent='JavaScript checked successfully'}catch(error){status.textContent='JavaScript syntax error: '+error.message}return}status.textContent=language+' has no runnable target'}document.querySelector('#newFile').onclick=newFile;document.querySelector('#runBtn').onclick=()=>void runCurrent();document.querySelector('#splitBtn').onclick=()=>{document.querySelector('#status').textContent='Split view is ready';setTimeout(()=>document.querySelector('#status').textContent='Ready',1400)};document.querySelectorAll('.menubar>button:not(#themeBtn):not(#paletteBtn)').forEach(b=>b.onclick=()=>{document.querySelector('#status').textContent=b.textContent+' menu';setTimeout(()=>document.querySelector('#status').textContent='Ready',1000)});addEventListener('vibeos:ready',async()=>{try{const saved=await window.vibeOS.state.read();if(saved.state?.tabs?.length)appState=saved.state;renderTree();openFile(appState.activeTabId||appState.tabs[0].id);window.vibeOS.state.subscribe(next=>{appState=next.state;renderTree();openFile(appState.activeTabId||appState.tabs[0].id)})}catch{renderTree();openFile('app.js')}finally{document.querySelector('#newFile').disabled=false}});renderTree();openFile('app.js');
function showOutput(text,meta,error=false){document.querySelector('#runOutput').textContent=text||'(no output)';document.querySelector('#runMeta').textContent=meta;document.querySelector('#status').textContent=error?'Run failed':'Run complete'}
async function runPython(){
  await save({download:false});
  showOutput('Running '+current+'…','Running');
  const source=editor.value;
  const operation={
    type:'process.run',
    appId:'app-sublime-text',
    program:'python3',
    args:['-'],
    stdin:source,
    timeoutMs:10000,
    context:{appId:'app-sublime-text',file:current}
  };
  try{
    const result=await window.vibeOS.request(operation);
    const out=typeof result==='string'?result:(result?.stdout||'');
    const err=result?.stderr||'';
    const code=result?.exitCode??result?.code??0;
    showOutput((out+(err?'\n'+err:'')).trim()||'(no output)','Exit '+code,code!==0);
  }catch(error){
    const message=error?.message||'The execution service is unavailable.';
    showOutput('Python run failed: '+message,'Run unavailable',true);
  }
}
document.querySelector('#runBtn').onclick=()=>languageFor(current)==='Python'?runPython():runCurrent();document.querySelector('#clearOutput').onclick=()=>showOutput('Run a Python file to see stdout and errors here.','No run yet');
const menuItems={fileMenu:[['New File','new'],['Save','save']],editMenu:[['Find','find']],viewMenu:[['Toggle Theme','theme']],toolsMenu:[['Run Current File','run']],helpMenu:[['About Sublime Text','about']]};
document.querySelector('#downloadBtn').onclick=()=>void save();
document.querySelectorAll('.menu-trigger').forEach(t=>t.onclick=()=>{document.querySelectorAll('.menu-popup').forEach(n=>n.remove());const p=document.createElement('div');p.className='menu-popup';p.style.left=t.offsetLeft+'px';p.style.top='32px';(menuItems[t.dataset.menu]||[['No commands','noop']]).forEach(([l,a])=>{const b=document.createElement('button');b.textContent=l;b.onclick=()=>{p.remove();if(a==='new')newFile();else if(a==='save')save();else if(a==='find'){findbar.classList.remove('hidden');findInput.focus()}else if(a==='theme')themeBtn.click();else if(a==='run')runCurrent();else if(a==='about')status.textContent='Sublime Text workspace'};p.append(b)});menuLayer.append(p)});
