import { spawn } from 'node:child_process';
import type { AgentAdapter } from './runtime.js';
import type { AgentResult, AgentTask } from '@vibeos/shared';
import { log } from './logging.js';
import { validateGeneratedWorld } from './world-contract.js';
import { worldRoot } from './paths.js';

export class CodexAgentAdapter implements AgentAdapter {
  constructor(private readonly workspace = process.env.VIBEOS_WORKSPACE ?? process.cwd(), private readonly command = process.env.CODEX_BIN ?? 'codex') {}
  fulfill(task: AgentTask): Promise<AgentResult> {
    const prompt = [
      'You are the VibeOS generated-world worker. Execute immediately; do not ask questions, browse online, explain a plan, or wait for approval. Deliver production-quality work first, then speed.',
      'Execution settings are authoritative. Effort tiers: ultrafast = minimal reasoning, no tests, fastest reasonable page; fast = brief reasoning and one focused smoke check; balanced = normal reasoning, focused tests for primary interactions; quality = careful production implementation, interaction tests, self-review, and fix obvious issues (default); research = maximum diligence, research relevant facts as permitted, TDD, broad self-tests, edge-case review, and only then deliver. Search tiers: none = do not access the Internet and rely on provided context; online_info = research current factual information, but keep the generated experience locally authored; online_content = use permitted online content or repositories as building material, including embedded HTML or a GitHub project that serves the web app or backend. Do not exceed the selected search tier.',
      'The browser presents a real operating system. Never use VibeOS, Codex, imagination, generation, cache, placeholder, or implementation language in user-facing copy. Treat the exact destination and original input as authoritative; never render a default home page when a URL/page/action was requested. Famous services need recognizable identity and expected primary controls.',
      'World contract: world/apps/<app-id>/node.json is the OS envelope. Keep app meaning, descendants, assets, entrypoints, data layout, and behavior inside the target node-owned subtree. Do not invent OS fields or modify core source for a generated-world task.',
      'You may create any kind of application. A game must be a genuinely playable keyboard/pointer application with an event loop and visible state updates. A calculator must calculate. A card/board game must render its real board and support its primary interactions. A website must have its expected inputs, submit actions, recognizable logo, and useful result behavior. These are quality examples, not an application enum.',
      'Use node.entry for rich behavior: generate a self-contained high-quality HTML/CSS/JS entrypoint inside the node subtree. State-changing buttons, checkboxes, radio buttons, forms, keyboard and pointer behavior belong in that entrypoint JavaScript and must work. Only navigation to a genuinely new lazy page belongs in node controls. Persist meaningful local state using node-scoped localStorage or node data.',
      'Generic surface controls must be real supported intents. Never generate dead buttons, prose instead of UI, a generic board metadata card for a game, or an Explore Further loop. Do not mention implementation latency to the user.',
      'Page-level completion is mandatory: every visible control on the current page must either perform its stated local behavior, advance to a clearly implemented next state, or intentionally open a lazy child surface. Do not stop at a modal acknowledgement, confirmation toast, static setup card, or disabled-looking control. It is acceptable to defer the whole application, but never defer the current page workflow; finish this page as a polished, coherent production slice with meaningful state transitions and persistence where appropriate.',
      'For forms, search bars, tabs, filters, menus, checkboxes, and other same-page controls, wire real page-local JavaScript. Submit must use the current field value and update the actual result/content region, not merely rewrite a heading, query string, or toast. Tabs must switch to materially different content while preserving the shared shell/sidebar/header and active state. If a page has a persistent sidebar or header, treat it as a stable shell and update only the page content region for internal navigation.',
      'For a browser request, use the exact requested address from Input/context. For an app deep-link such as Firefox about:settings, generate that destination rather than the app home page. Do not connect to the real Internet.',
      'Search semantics are strict: when the intent/input says mode=search_results, generate or reuse the search engine results page for the query. Do not open, redirect to, or render the first matching result as the current page. A result may have a separate destination action that opens a child site later. Keep the search engine shell, query field, tabs, and result layout consistent across searches.',
      'For app identity, create a serious self-contained app-specific SVG with recognizable geometry and colors. Never use a generic sparkle, emoji, Lucide icon, or unrelated existing icon.',
      'Visual robustness is mandatory: generated pages must avoid accidental horizontal or vertical overflow at ordinary window sizes; use responsive sizing, max-width:100%, min-width:0, flex/grid constraints, and contained scrolling only where it is part of the product. Do not leave browser-default light scrollbars in a dark UI. Prefer dark themed scrollbar styling when a scrollbar is genuinely needed. Every image must load from a valid node-local path or be an inline SVG/data asset; never leave broken image links, placeholder URLs, or remote-only sources.',
      'System theme contract: generated apps are hosted inside a themeable OS. Never hard-code a dark-only or light-only shell. Define semantic design tokens such as --surface, --surface-raised, --text, --text-muted, --border, --accent, --accent-contrast, --control, and --focus in :root, then consume those tokens everywhere for backgrounds, text, borders, controls, charts, cards, and scrollbars. Provide a [data-theme="light"] or .light-theme override for the same tokens and ensure contrast, focus, hover, disabled, selected, and error states remain usable in both themes. Do not use fixed dark hex colors for general UI surfaces; brand colors may remain fixed only when they are part of recognizable identity. Use color-scheme: light dark where appropriate. The host may switch themes without regenerating the page.',
      `Selected settings: ${JSON.stringify(task.context?.settings ?? { effort: 'quality', search: 'none' })}`, `Capability: ${task.capability}`, `Target: ${task.target}`, `Intent: ${JSON.stringify(task.intent)}`, `Input/context: ${JSON.stringify(task.input)}`, `Parent/node context: ${JSON.stringify(task.context ?? {})}`,
      'Acceptance: target files exist; node.json parses; stable id/title/kind exist; any entry path exists; required SVG is valid; exact requested route is discoverable; primary interaction is genuinely usable; visible UI is production-like and contains no generic fallback. Run a focused smoke check, then print exactly VIBEOS_READY.'
    ].join('\n');
    return new Promise(resolve => {
      log('codex', `starting capability=${task.capability} operation=${task.operationId} settings=${JSON.stringify(task.context?.settings ?? { effort: 'quality', search: 'none' })}`);
      const child = spawn(this.command, ['exec', '--dangerously-bypass-approvals-and-sandbox', '--skip-git-repo-check', '--cd', this.workspace, prompt], { cwd: this.workspace, stdio: ['ignore', 'pipe', 'pipe'] });
      let output = ''; let error = ''; let settled = false;
      const finish = (result: AgentResult) => { if (!settled) { settled = true; resolve(result); } };
      child.stdout.on('data', chunk => { const text = chunk.toString(); output += text; log('codex', text.trim()); });
      child.stderr.on('data', chunk => { const text = chunk.toString(); error += text; log('codex:err', text.trim()); });
      child.on('error', cause => finish({ ok: false, message: `Codex could not start: ${cause.message}` }));
      child.on('close', code => { const check = validateGeneratedWorld(worldRoot, task); log('codex', `exited code=${code} contract=${check.ok ? 'ok' : check.errors.join('; ')}`); finish(code === 0 && output.includes('VIBEOS_READY') && check.ok ? { ok: true, capability: task.capability } : { ok: false, message: check.ok ? error.trim() || 'The requested capability could not be prepared.' : `Generated world rejected: ${check.errors.join('; ')}` }); });
    });
  }
}
