import { spawn } from 'node:child_process';
import type { AgentAdapter } from './runtime.js';
import type { AgentResult, AgentTask } from '@vibeos/shared';
import { log } from './logging.js';

export class CodexAgentAdapter implements AgentAdapter {
  constructor(private readonly workspace = process.env.VIBEOS_WORKSPACE ?? process.cwd(), private readonly command = process.env.CODEX_BIN ?? 'codex') {}
  fulfill(task: AgentTask): Promise<AgentResult> {
    const prompt = ['You are the VibeOS generated-world worker. Execute now; do not ask questions, browse the repository, explain a plan, or wait for approval. Quality matters, but speed matters: make the smallest complete high-quality change and return immediately after validation.', 'System contract: browser UI is a real OS. Generation is invisible implementation latency. The runtime preserves the user intent, opens a loading surface, and after VIBEOS_READY reloads tracked world files and resumes the same surface. Never edit core TypeScript/React/config/package/test files for generated-world tasks.', 'World contract: root is world/apps/<app-id>/node.json. Recursive children live in world/apps/<app-id>/children/<child-id>/node.json. A node may have surface { heading, body, controls[] }; control intent is a valid VibeOS intent such as { type: "open_surface", appId, route }. Routes must be represented as child nodes or the app root route; do not invent unsupported runtime fields. The runtime discovers only node.json files, then reloads them.', 'For app:identity: create world/apps/<id>/node.json with id/title/kind/status=placeholder/icon/children; create world/apps/<id>/icon.svg. The SVG must be serious, recognizable, app-specific, self-contained SVG with deliberate geometry/colors matching the app. Never use generic Sparkles, emoji, Lucide, or an unrelated existing icon. Keep status placeholder until the first surface is generated.', 'For surface:<app>:<route>: create/update the exact app subtree with the requested route represented by a node.json; include complete useful content and controls. Do not return a generic Explore further control. Every control must advance the user’s original action or provide a meaningful app action. Preserve the root surface as the app’s initial screen; opening the app later must return to route /.', 'For Assistant repair: inspect the supplied complaint/context/log, edit only the smallest affected tracked subtree, validate JSON/SVG, and fix the reported behavior.', `Capability: ${task.capability}`, `Target: ${task.target}`, `Intent: ${JSON.stringify(task.intent)}`, `Input/context: ${JSON.stringify(task.input)}`, 'Acceptance: files are written at Target, JSON is valid, SVG is valid, behavior is complete, then print exactly VIBEOS_READY.'].join('\n');
    return new Promise(resolve => { log('codex', `starting capability=${task.capability} operation=${task.operationId}`); const child = spawn(this.command, ['exec', '--dangerously-bypass-approvals-and-sandbox', '--skip-git-repo-check', '--cd', this.workspace, prompt], { cwd: this.workspace, stdio: ['ignore', 'pipe', 'pipe'] }); let output = ''; let error = ''; let settled = false; const finish = (result: AgentResult) => { if (!settled) { settled = true; resolve(result); } }; child.stdout.on('data', chunk => { const text = chunk.toString(); output += text; log('codex', text.trim()); }); child.stderr.on('data', chunk => { const text = chunk.toString(); error += text; log('codex:err', text.trim()); }); child.on('error', cause => finish({ ok: false, message: `Codex could not start: ${cause.message}` })); child.on('close', code => { log('codex', `exited code=${code}`); finish(code === 0 && output.includes('VIBEOS_READY') ? { ok: true, capability: task.capability } : { ok: false, message: error.trim() || 'The requested capability could not be prepared.' }); }); });
  }
}
