import { spawn } from 'node:child_process';
import type { AgentAdapter } from './runtime.js';
import type { AgentResult, AgentTask } from '@vibeos/shared';
import { log } from './logging.js';

export class CodexAgentAdapter implements AgentAdapter {
  constructor(private readonly workspace = process.env.VIBEOS_WORKSPACE ?? process.cwd(), private readonly command = process.env.CODEX_BIN ?? 'codex') {}
  fulfill(task: AgentTask): Promise<AgentResult> {
    const prompt = ['You are the generated-world worker inside VibeOS.', 'Finish the requested implementation as fast as possible, then hand control back immediately. The browser must continue as if this app/page/behavior always existed and only took time to load.', 'For app identity generation, create or update node.json and a serious, recognizable, app-specific icon.svg in the exact target directory. Never use a generic Sparkles icon, emoji, Lucide icon, or unrelated existing asset. The SVG should have deliberate geometry, palette, and symbolism matching the app name.', 'For generated-world work, write only structured JSON, serious app-specific SVG, and assets under the exact target subtree. For Assistant repairs, inspect the reported context and recent logs, modify the smallest affected tracked world subtree, validate it, and do not touch core source unless the request explicitly identifies a core defect.', 'Do not narrate a plan or wait for confirmation. Perform the work now. End your response with exactly: VIBEOS_READY.', `Capability: ${task.capability}`, `Target path: ${task.target}`, `Original intent: ${JSON.stringify(task.intent)}`, `Input/context: ${JSON.stringify(task.input)}`].join('\n');
    return new Promise(resolve => { log('codex', `starting capability=${task.capability} operation=${task.operationId}`); const child = spawn(this.command, ['exec', '--dangerously-bypass-approvals-and-sandbox', '--skip-git-repo-check', '--cd', this.workspace, prompt], { cwd: this.workspace, stdio: ['ignore', 'pipe', 'pipe'] }); let output = ''; let error = ''; let settled = false; const finish = (result: AgentResult) => { if (!settled) { settled = true; resolve(result); } }; child.stdout.on('data', chunk => { const text = chunk.toString(); output += text; log('codex', text.trim()); }); child.stderr.on('data', chunk => { const text = chunk.toString(); error += text; log('codex:err', text.trim()); }); child.on('error', cause => finish({ ok: false, message: `Codex could not start: ${cause.message}` })); child.on('close', code => { log('codex', `exited code=${code}`); finish(code === 0 && output.includes('VIBEOS_READY') ? { ok: true, capability: task.capability } : { ok: false, message: error.trim() || 'The requested capability could not be prepared.' }); }); });
  }
}
