const marker = "data-vibeos-frame-bridge";
// This is appended at the end of the document head, after authored styles. It
// deliberately affects only the generic text baseline and form controls: a
// generated world can still use an intentional display face for branded art or
// a game HUD, while ordinary interface text follows the OS setting.
const typographyOverride = `<style data-vibeos-typography-override>:root{font-family:var(--vibe-font-ui)!important;font-size:var(--vibe-text-body)}body{font-family:var(--vibe-font-ui)!important;font-size:inherit}button,input,textarea,select{font:inherit}code,pre,kbd,.monospace{font-family:var(--vibe-font-mono)!important}</style>`;
const source = String.raw`<style data-vibeos-typography>:root{--vibe-font-ui:Inter,ui-sans-serif,system-ui,sans-serif;--vibe-font-mono:"DM Mono",ui-monospace,SFMono-Regular,Menlo,monospace;--vibe-scale:1;--vibe-text-caption:calc(11px * var(--vibe-scale));--vibe-text-label:calc(12px * var(--vibe-scale));--vibe-text-body:calc(14px * var(--vibe-scale));--vibe-text-title:calc(18px * var(--vibe-scale));--vibe-text-heading:calc(24px * var(--vibe-scale));--vibe-text-display:calc(34px * var(--vibe-scale));--vibe-line-tight:1.15;--vibe-line-normal:1.5}:root[data-ui-typeface="system"]{--vibe-font-ui:system-ui,-apple-system,"Segoe UI",sans-serif}:root[data-ui-typeface="accessible"]{--vibe-font-ui:Arial,Helvetica,sans-serif}:root[data-mono-typeface="system"]{--vibe-font-mono:ui-monospace,monospace}:root[data-mono-typeface="accessible"]{--vibe-font-mono:"Courier New",monospace}:root[data-display-scale="compact"]{--vibe-scale:.8}:root[data-display-scale="comfortable"]{--vibe-scale:1.1}:root[data-display-scale="large"]{--vibe-scale:1.25}:root[data-display-scale="extra_large"]{--vibe-scale:1.5}body{font-family:var(--vibe-font-ui)!important;font-size:var(--vibe-text-body)}code,pre,kbd,.monospace{font-family:var(--vibe-font-mono)!important}</style><script data-vibeos-frame-bridge>(function(){
  const pending=new Map(),commands=new Map(),contextMenus=new Map();let channel,contextProvider,imeEnabled=false,imeComposing=false;
  function imeAnchor(target){const rect=target&&target.getBoundingClientRect?target.getBoundingClientRect():null;return rect?{x:rect.left+Math.min(rect.width,Math.max(8,rect.width*.15)),y:rect.bottom+6}:undefined}
  function insertImeText(text){const target=document.activeElement;if(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement){const start=target.selectionStart??target.value.length,end=target.selectionEnd??start;target.setRangeText(text,start,end,"end");target.dispatchEvent(new InputEvent("input",{bubbles:true,inputType:"insertText",data:text}));return}if(target&&target.isContentEditable){document.execCommand("insertText",false,text);target.dispatchEvent(new InputEvent("input",{bubbles:true,inputType:"insertText",data:text}))}}
  function send(operation){return new Promise((resolve,reject)=>{if(!channel){reject(new Error("VibeOS bridge is not ready"));return}const requestId=crypto.randomUUID();const timer=setTimeout(()=>{pending.delete(requestId);reject(new Error("VibeOS operation timed out"))},60000);pending.set(requestId,{resolve,reject,timer});parent.postMessage({type:"vibeos:request",channel,requestId,operation},"*")})}
  addEventListener("message",event=>{const message=event.data;if(!message||typeof message!=="object")return;
    if(message.type==="vibeos:init"&&typeof message.channel==="string"){channel=message.channel;document.documentElement.dataset.theme=message.theme;if(message.typography)applyTypography(message.typography);dispatchEvent(new Event("vibeos:ready"));return}
    if(message.type==="vibeos:theme"&&message.channel===channel){document.documentElement.dataset.theme=message.theme;if(message.typography)applyTypography(message.typography)}
    if(message.type==="vibeos:ime-state"&&message.channel===channel){imeEnabled=!!message.enabled;imeComposing=!!message.composing;return}
    if(message.type==="vibeos:ime-commit"&&message.channel===channel){insertImeText(String(message.text||""));return}
    if(message.type==="vibeos:state"&&message.channel===channel){for(const listener of listeners)listener(message.state);return}
    if(message.type==="vibeos:context-menu-result"&&message.channel===channel){const item=contextMenus.get(message.requestId);if(!item)return;contextMenus.delete(message.requestId);item.resolve(message.id||null);return}
    if(message.type==="vibeos:result"&&message.channel===channel){const item=pending.get(message.requestId);if(!item)return;pending.delete(message.requestId);clearTimeout(item.timer);message.ok?item.resolve(message.value):item.reject(new Error(message.error||"Operation failed"))}
  });
  function applyTypography(value){if(!value||typeof value!=="object")return;const root=document.documentElement;root.dataset.uiTypeface=String(value.uiTypeface||"modern");root.dataset.monoTypeface=String(value.monoTypeface||"modern");root.dataset.displayScale=String(value.displayScale||"default")}
  const listeners=new Set();
  addEventListener("pointerdown",()=>{if(channel)parent.postMessage({type:"vibeos:focus",channel},"*")},true);
  addEventListener("keydown",event=>{if((event.ctrlKey||event.metaKey)&&!event.shiftKey&&event.key.toLowerCase()==="k"){event.preventDefault();event.stopPropagation();parent.postMessage({type:"vibeos:command-palette",channel,context:contextProvider?contextProvider():undefined,commands:[...commands.values()]},"*")}},true);
  addEventListener("keydown",event=>{const target=document.activeElement;if((event.ctrlKey||event.metaKey)&&event.code==="Space"){event.preventDefault();parent.postMessage({type:"vibeos:ime-toggle",channel},"*");return}if(!imeEnabled||!target||!(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target.isContentEditable)||event.ctrlKey||event.metaKey||event.altKey)return;const letter=/^[a-z]$/i.test(event.key),managed=letter||(imeComposing&&(event.key==="Backspace"||event.key==="Escape"||event.key===" "||event.key==="Enter"||event.key==="ArrowDown"||event.key==="ArrowUp"||/^[1-9]$/.test(event.key)));if(!managed)return;parent.postMessage({type:"vibeos:ime-key",channel,key:event.key,anchor:imeAnchor(target)},"*");event.preventDefault()},true);
  function openContextMenu(items,point){return new Promise(resolve=>{if(!channel){resolve(null);return}const requestId=crypto.randomUUID();contextMenus.set(requestId,{resolve});parent.postMessage({type:"vibeos:context-menu",channel,requestId,items:Array.isArray(items)?items:[],point},"*")})}
  window.vibeOS=Object.freeze({request:send,notify:(message,options)=>send({type:"notify",message,level:options&&options.level,timeoutMs:options&&options.timeoutMs}),navigate:(url,mode)=>send({type:"navigate",url,mode}),storage:Object.freeze({read:key=>send({type:"storage.read",key}),write:(key,value)=>send({type:"storage.write",key,value})}),state:Object.freeze({read:()=>send({type:"state.read"}),write:(state,revision)=>send({type:"state.write",state,revision}),subscribe:listener=>{listeners.add(listener);return()=>listeners.delete(listener)}}),dispatch:intent=>send({type:"dispatch",intent}),ai:Object.freeze({command:(command,options)=>send({type:"ai.command",command,scope:options&&options.scope,context:options&&options.context,output:options&&options.output})}),commands:Object.freeze({register:command=>{const id=String(command&&command.id||"");if(!id)throw new Error("Command id is required");commands.set(id,{id,title:String(command.title||id),detail:command.detail,context:command.context});return()=>commands.delete(id)},setContext:provider=>{contextProvider=typeof provider==="function"?provider:undefined}}),contextMenu:Object.freeze({open:openContextMenu})});
  parent.postMessage({type:"vibeos:ready"},"*");
})();</script>`;
export function injectFrameBridge(html: string) {
  if (html.includes(marker)) return html;
  const head = html.match(/<head(?:\s[^>]*)?>/i);
  if (head?.index !== undefined) {
    const injected = html.slice(0, head.index + head[0].length) + source + html.slice(head.index + head[0].length);
    const close = injected.match(/<\/head\s*>/i);
    if (close?.index !== undefined) return injected.slice(0, close.index) + typographyOverride + injected.slice(close.index);
    return injected + typographyOverride;
  }
  return source + html;
}
