const defaults={selected:'Cube',mode:'select',wire:false,grid:true,view:'perspective',orbitX:56,orbitZ:-38,zoom:1,objects:[{name:'Cube',type:'Mesh',color:'#8b7cf6',x:0,y:1,z:0,rx:0,ry:0,rz:0,sx:1,sy:1,sz:1,vertices:8,faces:6},{name:'Ground',type:'Plane',color:'#536078',x:0,y:0,z:0,rx:0,ry:0,rz:0,sx:4,sy:4,sz:4,vertices:4,faces:1},{name:'Camera',type:'Camera',color:'#e6b84b',x:4,y:3,z:5,rx:-18,ry:38,rz:0,sx:1,sy:1,sz:1,vertices:0,faces:0}]};let state=structuredClone(defaults),history=[],future=[],playing=false,playTimer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
async function boot(){try{const saved=await window.vibeOS?.storage.read('model-studio-scene');if(saved?.objects)state={...defaults,...saved}}catch{}render();}
function selected(){return state.objects.find(o=>o.name===state.selected)||state.objects[0]}
function persist(){window.vibeOS?.storage.write('model-studio-scene',state);$('#scene-status').textContent='Saving…';setTimeout(()=>$('#scene-status').textContent='All changes saved',500)}
function commit(){history.push(JSON.stringify(state));if(history.length>30)history.shift();future=[];persist();render()}
function render(){const o=selected();$('#scene-tree').innerHTML=state.objects.map(x=>`<div class="tree-item ${x.name===state.selected?'selected':''}" data-name="${x.name}"><span class="tree-icon">${x.type==='Camera'?'◇':x.type==='Plane'?'▱':'◈'}</span><span>${x.name}</span><span class="tree-eye">${x.hidden?'○':'●'}</span></div>`).join('');$('#selected-name').textContent=o.name;$('#selected-type').textContent=`${o.type} · ${o.faces?o.faces*2+' tris':'Perspective'}`;$('#vertices').textContent=o.vertices;$('#faces').textContent=o.faces;$('#dimensions').textContent=`${(2*o.sx).toFixed(1)} × ${(2*o.sy).toFixed(1)} × ${(2*o.sz).toFixed(1)} m`;$$('[data-prop]').forEach(i=>i.value=o[i.dataset.prop]);const stage=$('#model-stage');stage.innerHTML=o.type==='Mesh'?'<div class="mesh"><i class="face front"></i><i class="face back"></i><i class="face right"></i><i class="face left"></i><i class="face top"></i><i class="face bottom"></i></div>':'<div class="mesh"><i class="face front"></i></div>';stage.style.setProperty('--mesh-color',o.color);stage.style.transform=`translate(calc(-50% + ${o.x*32}px),calc(-50% - ${o.y*32}px + ${o.z*18}px)) rotateX(${state.orbitX}deg) rotateZ(${state.orbitZ}deg) scale(${state.zoom})`;stage.classList.toggle('hidden',!!o.hidden);$('#viewport').classList.toggle('wire',state.wire);$('#floor-grid').classList.toggle('off',!state.grid);$('.gizmo').style.display=o.type==='Camera'?'none':'block';$$('.tool').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));$$('.view-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
$$('.tool').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;render();toast(`${b.textContent.trim()} tool active`)});$$('.view-tab').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();toast(`${b.textContent} view`)});
$('#scene-tree').onclick=e=>{const row=e.target.closest('.tree-item');if(row){state.selected=row.dataset.name;render()}};
$('#add-object').onclick=()=>{const n=state.objects.filter(o=>o.type==='Mesh').length+1;history.push(JSON.stringify(state));state.objects.unshift({name:`Cube ${n}`,type:'Mesh',color:'#31c48d',x:0,y:1,z:0,rx:0,ry:0,rz:0,sx:1,sy:1,sz:1,vertices:8,faces:6});state.selected=`Cube ${n}`;commit();toast('New cube added')};
$$('[data-prop]').forEach(i=>i.onchange=()=>{const o=selected();history.push(JSON.stringify(state));o[i.dataset.prop]=Number(i.value)||0;commit()});$('#reset-transform').onclick=()=>{history.push(JSON.stringify(state));Object.assign(selected(),{x:0,y:1,z:0,rx:0,ry:0,rz:0,sx:1,sy:1,sz:1});commit();toast('Transform reset')};
$('#visibility').onclick=()=>{history.push(JSON.stringify(state));selected().hidden=!selected().hidden;commit();toast(selected().hidden?'Object hidden':'Object visible')};$('#wireframe').onclick=()=>{state.wire=!state.wire;render();toast(state.wire?'Wireframe on':'Wireframe off')};$('#grid-toggle').onclick=()=>{state.grid=!state.grid;render()};$('#frame').onclick=()=>toast(`Framed ${state.selected}`);
$$('.inspector-tab').forEach(b=>b.onclick=()=>{$$('.inspector-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#object-inspector').classList.toggle('hidden',b.dataset.inspect!=='object');$('#material-inspector').classList.toggle('hidden',b.dataset.inspect!=='material')});
$$('#swatches button').forEach(b=>b.onclick=()=>{history.push(JSON.stringify(state));selected().color=b.dataset.color;commit();$$('#swatches button').forEach(x=>x.style.outline=x===b?'2px solid var(--vibe-accent)':'none')});['roughness','metallic'].forEach(id=>$('#'+id).oninput=e=>$('#'+id+'-value').textContent=e.target.value+'%');
$$('.select-row').forEach(b=>b.onclick=()=>{$$('.select-row').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.select-row span').forEach(x=>x.textContent='');b.querySelector('span').textContent='✓';toast(b.textContent.trim())});
$('#save').onclick=()=>{persist();toast('Scene saved')};$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='model-scene.json';a.click();URL.revokeObjectURL(a.href);toast('Scene exported')};
$('#undo').onclick=()=>{if(history.length){future.push(JSON.stringify(state));state=JSON.parse(history.pop());render();persist();toast('Undid last change')}};$('#redo').onclick=()=>{if(future.length){history.push(JSON.stringify(state));state=JSON.parse(future.pop());render();persist();toast('Redid change')}};
$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'Ⅱ':'▶';if(playing){let t=0;playTimer=setInterval(()=>{$('#timecode').textContent=`00:${(t/100).toFixed(2).padStart(5,'0')}`;t=(t+1)%240},10)}else clearInterval(playTimer)};$('#add-key').onclick=()=>toast(`Keyframe added at ${$('#timecode').textContent}`);
let drag=null;$('#viewport').addEventListener('pointerdown',e=>{if(e.button!==0)return;const hit=e.target.closest('#model-stage');if(hit&&!selected().hidden&&selected().type==='Mesh'){drag={kind:'object',x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,before:JSON.stringify(state)};hit.setPointerCapture(e.pointerId)}else{drag={kind:'orbit',x:e.clientX,y:e.clientY,orbitX:state.orbitX,orbitZ:state.orbitZ};$('#viewport').setPointerCapture(e.pointerId)}$('#viewport').classList.add('dragging')});$('#viewport').addEventListener('pointermove',e=>{if(!drag)return;if(drag.kind==='object'){const o=selected();o.x+=((e.clientX-drag.lastX)/32);o.z+=((e.clientY-drag.lastY)/18);drag.lastX=e.clientX;drag.lastY=e.clientY}else{state.orbitZ=drag.orbitZ+(e.clientX-drag.x)*.45;state.orbitX=Math.max(12,Math.min(84,drag.orbitX-(e.clientY-drag.y)*.45))}render()});const endDrag=()=>{if(drag){if(drag.kind==='object'){history.push(drag.before);persist();toast(`${selected().name} moved`)}else persist();drag=null;$('#viewport').classList.remove('dragging');render()}};$('#viewport').addEventListener('pointerup',endDrag);$('#viewport').addEventListener('pointercancel',endDrag);$('#viewport').addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.55,Math.min(1.8,state.zoom*(e.deltaY<0?1.08:.92)));render()},{passive:false});
$('#viewport').onkeydown=e=>{if(e.key.toLowerCase()==='f')$('#frame').click();if(['v','g','r','s'].includes(e.key.toLowerCase())){$(`[data-mode="${({v:'select',g:'move',r:'rotate',s:'scale'})[e.key.toLowerCase()]}"]`).click()}};boot();
