import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Calculator, FileText, Folder, Globe, Search, Settings, Terminal, X, Store, Sparkles, MessageCircle } from 'lucide-react';
import type { AppId, Intent, Operation, RuntimeEvent, RuntimeSnapshot, WindowModel, RuntimeIntent } from '@vibeos/shared';
import './styles.css';

const appInfo: Record<string, { label: string; icon: typeof Folder; color: string }> = {
  files: { label: 'Files', icon: Folder, color: '#f4b942' }, calculator: { label: 'Calculator', icon: Calculator, color: '#75a4ff' }, assistant: { label: 'Assistant', icon: MessageCircle, color: '#9b8cff' },
  editor: { label: 'Text Editor', icon: FileText, color: '#ee8fb7' }, browser: { label: 'Browser', icon: Globe, color: '#7ed7bb' }, settings: { label: 'Settings', icon: Settings, color: '#a89dfc' }, shop: { label: 'App Shop', icon: Store, color: '#f08c62' },
};
const initial: RuntimeSnapshot = { windows: [], operations: [], notifications: [], apps: [], surfaces: [] };

function App() {
  const [snapshot, setSnapshot] = useState(initial); const [search, setSearch] = useState(''); const [launcher, setLauncher] = useState(false); const [notice, setNotice] = useState(''); const [connected, setConnected] = useState(false); const [queued, setQueued] = useState<RuntimeIntent[]>([]);
  const [socket, setSocket] = useState<WebSocket | null>(null);
  useEffect(() => { const connection = new WebSocket(import.meta.env.VITE_OS_SOCKET ?? 'ws://localhost:8787'); connection.onopen = () => { console.info('[vibeos] backend connected'); setConnected(true); setSocket(connection); }; connection.onclose = () => { console.info('[vibeos] backend disconnected'); setConnected(false); setSocket(null); }; connection.onerror = () => { setConnected(false); setNotice('VibeOS backend connection failed.'); }; connection.onmessage = event => { const message = JSON.parse(event.data) as RuntimeEvent; console.info('[vibeos:event]', message); setSnapshot(current => reduce(current, message)); if (message.type === 'notification') { setNotice(message.message); setTimeout(() => setNotice(''), 3500); } if (message.type === 'trace' && message.message.startsWith('failed')) setNotice(message.message); }; return () => connection.close(); }, []);
  useEffect(() => { if (!socket || socket.readyState !== WebSocket.OPEN || queued.length === 0) return; queued.forEach(intent => socket.send(JSON.stringify(intent))); setQueued([]); }, [socket, queued]);
  const runtimeApps = snapshot.apps.filter(app => app.installed); const visibleApps = runtimeApps.filter(app => app.name.toLowerCase().includes(search.toLowerCase()));
  const dispatch = (intent: RuntimeIntent) => { if (socket?.readyState === WebSocket.OPEN) socket.send(JSON.stringify(intent)); else setQueued(current => [...current, intent]); setLauncher(false); };
  const pending = snapshot.operations.filter(operation => operation.state === 'pending').length + queued.length;
  const iconUrl = (app: RuntimeSnapshot['apps'][number]) => `${(import.meta.env.VITE_OS_HTTP ?? 'http://localhost:8787')}/assets/apps/${encodeURIComponent(app.id)}/icon.svg`;
  return <main className="os" onContextMenu={event => event.preventDefault()}>
    <div className="wallpaper"><div className="orb orb-one"/><div className="orb orb-two"/></div>
    <header className="topbar"><span className="brand">VibeOS</span><span className="topbar-center">{snapshot.windows.find(w => w.focused)?.title ?? 'Desktop'}</span><span className="clock">{new Intl.DateTimeFormat([], { hour: 'numeric', minute: '2-digit' }).format(new Date())}</span></header>
    <section className="desktop" onDoubleClick={() => setLauncher(true)}>
      {snapshot.windows.length === 0 && <div className="welcome"><div className="welcome-mark">V</div><h1>Welcome home.</h1><p>Everything you need, right where you left it.</p><button onClick={() => setLauncher(true)}>Open launcher <span>⌘ K</span></button></div>}
      {snapshot.windows.map(window => <Window key={window.id} window={window} onClose={() => dispatch({ type: 'close_window', windowId: window.id })} onAction={dispatch} snapshot={snapshot} />)}
    </section>
    <nav className="dock">{runtimeApps.slice(0, 6).map(app => { const info = appInfo[app.id]; const Icon = info?.icon ?? Sparkles; return <button key={app.id} className="dock-item" title={app.name} onClick={() => dispatch({ type: 'open_app', appId: app.id })}>{app.icon.endsWith('.svg') ? <img className="app-svg" src={iconUrl(app)} alt=""/> : <Icon size={22} color={info?.color ?? '#d5a6ff'}/>} {snapshot.windows.some(w => w.appId === app.id) && <i/>}</button>; })}<button className="dock-item launcher-button" onClick={() => setLauncher(true)}><Search size={22}/></button></nav>
    {launcher && <div className="launcher-backdrop" onClick={() => setLauncher(false)}><div className="launcher" onClick={event => event.stopPropagation()}><div className="searchbox"><Search size={20}/><input autoFocus placeholder="Search apps" value={search} onChange={event => setSearch(event.target.value)} /></div><div className="app-grid">{visibleApps.map(app => { const info = appInfo[app.id]; const Icon = info?.icon ?? Sparkles; return <button key={app.id} className="app-tile" onClick={() => dispatch({ type: 'open_app', appId: app.id })}><span className="app-icon" style={{ background: info?.color ?? '#c69cff' }}>{app.icon.endsWith('.svg') ? <img className="app-svg" src={iconUrl(app)} alt=""/> : <Icon size={24}/>}</span><span>{app.name}</span></button>; })}</div>{visibleApps.length === 0 && search && <div className="empty-search">No app installed yet for “{search}”.</div>}</div></div>}
    {pending > 0 && <div className="loading-pill"><span className="spinner"/>Opening…</div>}
    {!connected && <div className="connection-pill">Connecting to VibeOS…</div>}
    {notice && <div className="notice"><Terminal size={17}/>{notice}</div>}
  </main>;
}

function Window({ window, onClose, onAction, snapshot }: { window: WindowModel; onClose: () => void; onAction: (intent: RuntimeIntent) => void; snapshot: RuntimeSnapshot }) {
  const surface = snapshot.surfaces.filter(item => item.appId === window.appId).at(-1); const app = snapshot.apps.find(item => item.id === window.appId); return <article className={`window ${window.state === 'maximized' ? 'maximized' : ''}`} onMouseDown={() => onAction({ type: 'focus_window', windowId: window.id })}><div className="window-bar"><span className="traffic"><button aria-label="Close window" onClick={event => { event.stopPropagation(); onClose(); }}><X size={11}/></button><b/><b/></span><span>{window.title}</span><span className="window-menu">•••</span></div><div className="window-body">{app?.status === 'placeholder' ? <PlaceholderView app={app}/> : window.appId === 'assistant' ? <AssistantView onAction={onAction} windowId={window.id}/> : window.appId === 'calculator' ? <CalculatorView/> : window.appId === 'browser' ? <BrowserView onAction={onAction} snapshot={snapshot}/> : window.appId === 'shop' ? <ShopView onAction={onAction} apps={snapshot.apps}/> : surface ? <SurfaceView surface={surface} onAction={onAction}/> : <PlaceholderView app={app ?? { id: window.appId, name: window.title, description: '', icon: 'sparkles', installed: true, status: 'placeholder' }}/>}</div></article>;
}
function AssistantView({ onAction, windowId }: { onAction: (intent: RuntimeIntent) => void; windowId: string }) { const [message, setMessage] = useState(''); const [sent, setSent] = useState(''); return <div className="assistant settings"><MessageCircle size={34}/><h2>Assistant</h2><p>Describe what feels wrong. VibeOS will repair the affected world.</p><textarea aria-label="Describe a problem" value={message} onChange={event => setMessage(event.target.value)} placeholder="Tell Assistant what to fix…"/><button onClick={() => { if (!message.trim()) return; setSent(message.trim()); onAction({ type: 'assistant_request', message: message.trim(), context: { windowId } }); setMessage(''); }}>Ask Assistant</button>{sent && <small>Working on: {sent}</small>}</div>; }
function CalculatorView() { const [display, setDisplay] = useState('0'); const [left, setLeft] = useState<number | null>(null); const [operator, setOperator] = useState<string | null>(null); const press = (key: string) => { if (/^\d$/.test(key) || key === '.') { setDisplay(display === '0' && key !== '.' ? key : display + key); return; } if (key === 'C') { setDisplay('0'); setLeft(null); setOperator(null); return; } if (key === '=') { if (left !== null && operator) { const right = Number(display); const value = operator === '+' ? left + right : operator === '−' ? left - right : operator === '×' ? left * right : right === 0 ? NaN : left / right; setDisplay(String(value)); setLeft(null); setOperator(null); } return; } setLeft(Number(display)); setOperator(key); setDisplay('0'); }; return <div className="calculator"><div className="calc-display">{display}</div><div className="calc-keys">{['C','7','8','9','÷','4','5','6','×','1','2','3','−','0','.','=','+'].map(key => <button key={key} onClick={() => press(key)}>{key}</button>)}</div></div>; }
function EditorView({ onAction }: { onAction: (intent: Intent) => void }) { return <div className="editor"><div className="editor-toolbar"><span>Untitled.txt</span><button onClick={() => onAction({ type: 'open_surface', appId: 'app-editor', route: '/save' })}>Save</button></div><textarea placeholder="Start writing..." /></div>; }
function FilesView({ onAction }: { onAction: (intent: Intent) => void }) { return <div className="files"><aside><strong>Locations</strong><button>⌂ Home</button><button>▣ Documents</button><button>↓ Downloads</button></aside><div className="file-content"><div className="file-heading"><h2>Home</h2><button onClick={() => onAction({ type: 'open_app', appId: 'app-editor' })}>New file</button></div><div className="file-row"><FileText size={20} color="#ee8fb7"/><span>Welcome.txt</span><small>Just now</small></div></div></div>; }
function BrowserView({ onAction, snapshot }: { onAction: (intent: RuntimeIntent) => void; snapshot: RuntimeSnapshot }) { const [url, setUrl] = useState(''); const surface = snapshot.surfaces.filter(item => item.appId === 'browser').at(-1); return <div className="browser"><form onSubmit={event => { event.preventDefault(); if (url.trim()) onAction({ type: 'navigate', target: url }); }}><input className="address" value={url} onChange={event => setUrl(event.target.value)} placeholder="Search or enter website" /></form>{surface ? <SurfaceView surface={surface} onAction={onAction}/> : <div className="browser-empty"><Globe size={42}/><h2>Where to?</h2><p>Imagine any website, locally.</p></div>}</div>; }
function ShopView({ onAction, apps }: { onAction: (intent: RuntimeIntent) => void; apps: RuntimeSnapshot['apps'] }) { const [query, setQuery] = useState(''); const installed = apps.filter(app => app.id !== 'shop' && app.name.toLowerCase().includes(query.toLowerCase())); return <div className="settings"><Store size={32}/><h2>App Shop</h2><input className="shop-input" aria-label="Search apps" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search any app"/><button onClick={() => query.trim() && onAction({ type: 'install_app', app: { id: `app-${query.toLowerCase().replace(/\W+/g, '-')}`, name: query.trim(), description: `Imagine and explore ${query}`, icon: 'sparkles' } })}>Imagine and install</button><div>{installed.map(app => <p key={app.id}>{app.name} · {app.status}</p>)}</div></div>; }
function SurfaceView({ surface, onAction }: { surface: RuntimeSnapshot['surfaces'][number]; onAction: (intent: RuntimeIntent) => void }) { if (surface.status !== 'ready') return <div className="browser-empty"><span className="spinner"/><h2>Preparing {surface.title}…</h2></div>; return <div className="browser-empty"><Sparkles size={42}/><h2>{surface.content.heading}</h2><p>{surface.content.body}</p>{surface.content.fields?.map(field => <input key={field.id} aria-label={field.label} placeholder={field.placeholder} defaultValue={field.value}/>)}{surface.content.controls.map(control => <button key={control.id} onClick={() => onAction(control.action)}>{control.label}</button>)}{(surface.content.links ?? []).map(link => <button key={link.id} onClick={() => onAction({ type: 'open_surface', appId: surface.appId, route: link.route })}>{link.label}</button>)}</div>; }
function SettingsView() { return <div className="settings"><Settings size={32}/><h2>Settings</h2><p>Personalize your VibeOS experience.</p></div>; }
function PlaceholderView({ app }: { app: RuntimeSnapshot['apps'][number] }) { return <div className="browser-empty"><Sparkles size={42}/><h2>{app.name}</h2><p>This app is ready to be imagined.</p></div>; }
function reduce(snapshot: RuntimeSnapshot, event: RuntimeEvent): RuntimeSnapshot { if (event.type === 'snapshot') return event.snapshot; if (event.type === 'window') return { ...snapshot, windows: [...snapshot.windows.filter(w => w.id !== event.window.id), event.window] }; if (event.type === 'surface') return { ...snapshot, surfaces: [...snapshot.surfaces.filter(s => s.id !== event.surface.id), event.surface] }; if (event.type === 'operation') return { ...snapshot, operations: [...snapshot.operations.filter(o => o.id !== event.operation.id), event.operation] }; return snapshot; }

createRoot(document.getElementById('root')!).render(<App/>);
